version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  icon: icon.svg
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/open-toolchain/default-toolchain](https://github.com/open-toolchain/default-toolchain)
    git branch: >-
      [master](https://github.com/open-toolchain/default-toolchain/tree/master)
toolchain:
  name: '{{form.pipeline.parameters.app-name}}'
  template:
    getting_started:
      $ref: '#/messages/toolchain.getting_started'
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_url: https://github.com/IBMDeveloperBR/Christmas-Challenge
      type: link
      has_issues: false
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{toolchain.name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          BRANCH: '{{branch}}'
          CF_APP: '{{form.pipeline.parameters.username}}-icc'
          CF_SPACE: '{{form.pipeline.parameters.dev-space}}'
          CF_ORGANIZATION: '{{form.pipeline.parameters.dev-organization}}'
          CF_REGION_ID: '{{form.pipeline.parameters.dev-region}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          NLU_URL: '{{form.pipeline.parameters.nlu-url}}'
          NLU_API_KEY: '{{form.pipeline.parameters.nlu-api-key}}'
          MODEL_ID: '{{form.pipeline.parameters.model-id}}'
          USERNAME: '{{form.pipeline.parameters.username}}'
        execute: true
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      dev-region: ''
      dev-organization: ''
      dev-space: ''
      app-name: '{{services.repo.parameters.repo_name}}'
    schema:
      $ref: deploy.json